name: ChunkCells
version: ${project.version}
main: dev.lightdream.chunkcells.Main
authors: [ L1ghtDream ]
website: https://lightdream.dev
depend:
  - WorldEdit
  - Cookies
commands:
  cc:
    description: NA